spring:
  application:
    name: persea-user-service
  datasource:
      url: jdbc:postgresql://localhost:5433/user_service
      username: postgres
      password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/persea
  kafka:
    bootstrap-servers: localhost:9094

kafka:
  topics:
    product-cdc: data.cdc.public.products
    product-outbox: data.cdc.product.outbox
  consumer-groups:
    product-sync: product-service.cdc.sync
    product-viewed: product-service.outbox.product-viewed

server:
  port: 8090