spring:
  application:
    name: persea-user-service
  datasource:
      url: jdbc:postgresql://localhost:5432/user_service
      username: postgres
      password: mysecretpassword
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/persea

server:
  port: 8082

logging:
  level:
    org:
      springframework:
        security: DEBUG